# Welcome to Jekyll!

# Website settings
title: "Remi Marenco"
description: "Remi Marenco: From Software Engineering passion to Computational Biology revolution"
keywords: "Remi, Marenco, Remi Marenco, Jekyll, Computational Biology, Galaxy Project, Bioinformatics"

baseurl: "/"
url: "http://www.marenco.remionramp.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Remi Marenco'
  first_name: 'Remi'
  last_name: 'Marenco'
  email: 'remi.marenco@gmail.com'
  facebook_username: 'remi.marenco'
  github_username: 'remimarenco'
  head_img: 'static/img/landing/Remi.jpg'

# social link
jingyu:
  first_name: 'Remi'
  last_name: 'Marenco'
  description: 'Passion for Software and Science'
  link: 'https://github.com/remimarenco'
  email: 'remi.marenco@gmail.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  hobbies: 'Hobbies'
  contact: 'Contact'

# my projects
project:
  saplatform:
    name: 'Saplatform'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/saplatform.jpg'
  jalpc:
    name: 'Jalpc'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.jpg'
  angularjs:
    name: 'Jalpc-A'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.jpg'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
